name: puzukkeni
description: An alarm app with integrated mini-game
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  intl: ^0.18.1
  uuid: ^3.0.7
  js: ^0.6.7
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  assets:
    # This line tells Flutter to include EVERY file inside the assets/images folder.
    # The slash at the end is important.
    - assets/images/

#  assets:
#    - assets/images/
#    - assets/sounds/
